// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0jvcxFP8ETf7Vep7oaV1Ff9sg4Hf4dH4',
    appId: '1:1046084502817:web:c516716bc598ced976aa60',
    messagingSenderId: '1046084502817',
    projectId: 'chatapp-39aea',
    authDomain: 'chatapp-39aea.firebaseapp.com',
    storageBucket: 'chatapp-39aea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JuuhmYGSmSrJbFYpofZxqUszifGY20w',
    appId: '1:1046084502817:android:ce5cb255ed14d77176aa60',
    messagingSenderId: '1046084502817',
    projectId: 'chatapp-39aea',
    storageBucket: 'chatapp-39aea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQOlFjshZgT4E5KDTNkAGOWbkeQBbj-xM',
    appId: '1:1046084502817:ios:51b1c7b6074b159076aa60',
    messagingSenderId: '1046084502817',
    projectId: 'chatapp-39aea',
    storageBucket: 'chatapp-39aea.appspot.com',
    iosBundleId: 'com.example.globalchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQOlFjshZgT4E5KDTNkAGOWbkeQBbj-xM',
    appId: '1:1046084502817:ios:51b1c7b6074b159076aa60',
    messagingSenderId: '1046084502817',
    projectId: 'chatapp-39aea',
    storageBucket: 'chatapp-39aea.appspot.com',
    iosBundleId: 'com.example.globalchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0jvcxFP8ETf7Vep7oaV1Ff9sg4Hf4dH4',
    appId: '1:1046084502817:web:4ca469f57871d93876aa60',
    messagingSenderId: '1046084502817',
    projectId: 'chatapp-39aea',
    authDomain: 'chatapp-39aea.firebaseapp.com',
    storageBucket: 'chatapp-39aea.appspot.com',
  );
}
